// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;

namespace MO5Emulator
{
	public partial class CheatWindowController : NSWindowController
	{
        public CheatViewController Controller => ContentViewController as CheatViewController;

		public CheatWindowController (IntPtr handle) : base (handle)
		{
		}

		partial void RemoveCheat(NSToolbarItem sender)
		{
			Controller.DeleteCheat(this.Window);
		}

		partial void EditCheat(NSToolbarItem sender)
		{
			Controller.EditCheat(this.Window);
		}

        partial void LoadCheats(NSToolbarItem sender)
        {
            Controller.LoadCheats(this.Window);
        }

		partial void SaveCheats(NSToolbarItem sender)
		{
			Controller.SaveCheats(this.Window);
		}

		public override void PrepareForSegue(NSStoryboardSegue segue, Foundation.NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			switch (segue.Identifier)
			{
				case "AddCheatSegue":
                    {
                        var editor = segue.DestinationController as AddCheatViewController;
                        editor.Presentor = ContentViewController as CheatViewController;
                        editor.Cheat = new CheatModel();

                        // Wire-up
                        editor.CheatModified += (o,cheat) =>
                        {
                            editor.Presentor.AddCheat(editor.Cheat);
                        };
                    }
					break;
			}
		}
	}
}
