// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;

namespace MO5Emulator
{
    [Register("IsTwoBytesSizeValueTransformer")]
    public class IsTwoBytesSizeValueTransformer : NSValueTransformer
    {
        public IsTwoBytesSizeValueTransformer(NSObjectFlag flag) : base(flag)
        {
        }

        public IsTwoBytesSizeValueTransformer(IntPtr handle) : base(handle)
        {
        }

        public override NSObject TransformedValue(NSObject value)
        {
            var number = value as NSNumber;
            if (number == null) return base.TransformedValue(value);

            return new NSNumber(number.Int32Value == 2);
        }

        public override NSObject ReverseTransformedValue(NSObject value)
        {
            var number = value as NSNumber;
            if (number == null) return base.TransformedValue(value);

            return new NSNumber(number.BoolValue ? 2 : 1);
        }
    }
}
