// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;

namespace MO5Emulator
{

    public partial class AddCheatViewController : NSViewController
	{
        private CheatModel _cheat;

        public NSViewController Presentor { get; internal set; }

        public event EventHandler CheatModified;

		[Export("Cheat")]
        public CheatModel Cheat
		{
			get { return _cheat; }
			set
			{
				WillChangeValue("Cheat");
				_cheat = value;
				DidChangeValue("Cheat");
			}
		}

        public AddCheatViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        
            var hexFormatter = new HexFormatter { Maximum = 0xFFFF };
            AddressTextField.Formatter = hexFormatter;
            AddButton.Activated += (sender, e) => AddCheat();
        }

        private bool Validate()
        {
            if (string.IsNullOrEmpty(AddressTextField.StringValue))
            {
                AddressTextField.SelectText(this);
                return false;
            }

            if (string.IsNullOrEmpty(ValueTextField.StringValue))
            {
                ValueTextField.SelectText(this);
                return false;
            }
            return true;
        }

        partial void ByteSize(NSButton sender)
        {
            ((NSNumberFormatter)ValueTextField.Formatter).Minimum = 0;
            ((NSNumberFormatter)ValueTextField.Formatter).Maximum = Math.Pow(2, Cheat.Size * 8) - 1;
        }

        private void AddCheat()
        {
            if (!Validate())
                return;
            
            CheatModified?.Invoke(this, EventArgs.Empty);
            CloseSheet();
        }

        partial void CancelCheat(NSButton sender)
        {
            CloseSheet();
        }

        private void CloseSheet()
        {
            DismissViewController(this);
        }
	}
}
